- hosts: all
  become: true
  vars:
   appname: nginx
   appstate: present
   servicestate: started
   packagestatus: yes

  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: "{{packagestatus}}"
      update_cache: "{{packagestatus}}"
  - name: installing "{{appname}}" software
    apt:
      name: "{{appname}}"
      state: "{{appstate}}"

  - name: start "{{appname}}" service
    service:
      name: "{{appname}}"
      state: "{{servicestate}}"