- hosts: all
  become: true
  vars:
   appname: apache2
   appstate: absent
   servicestate: stopped

  tasks:
  - name: installing "{{appname}}" software
    apt:
      name: "{{appname}}"
      state: "{{appstate}}"

  - name: start "{{appname}}" service
    service:
      name: "{{appname}}"
      state: "{{servicestate}}"