- hosts: webservers
  become: true
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      #cache_valid_time: 86400 
  - name: stopping jenkins software
    apt:
      name: jenkins
      state: absent

  - name: stop jenkins service
    service:
      name: jenkins
      state: stopped